# Generated by Django 5.0.1 on 2024-01-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=155)),
                ("last_name", models.CharField(blank=True, max_length=155, null=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                ("contacted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="courses/")),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=155)),
                ("last_name", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="teachers/teacher.jpg",
                        upload_to="teachers/",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=100)),
                ("sub_title", models.CharField(blank=True, max_length=255, null=True)),
                ("background_image", models.ImageField(upload_to="background/")),
            ],
        ),
        migrations.CreateModel(
            name="EnrollCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("contacted", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_enrollment",
                        to="home.course",
                    ),
                ),
            ],
        ),
    ]
