# Generated by Django 5.0.1 on 2024-01-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
