# Generated by Django 3.2.23 on 2024-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teacher_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default='testimonials/student-avathar.jpg', upload_to='testimonials/')),
                ('review', models.TextField()),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
